In [21]:
import pandas as pd
import spacy
from collections import defaultdict 
from spacy import displacy
import random
from spacy.training import Example
from spacy.pipeline import EntityRecognizer
from typing import List, Tuple
from sentence_transformers import SentenceTransformer
import nltk
from nltk.corpus import stopwords
import string
import re
import numpy as np
from tqdm import tqdm

# 1. Загрузка датасета

In [22]:
df = pd.read_json("../../data/data.txt", lines=True)
final_df = df.copy()

# 2. Используем стандартную NER-модель

In [23]:
# Загружаем модель для русского языка
# если она не найдена, то установим командой: python -m spacy download ru_core_news_lg
# также попробовать deeppavlovru_core_news_lg - https://chat.deepseek.com/a/chat/s/3d0a9423-ea38-4e29-8dc5-63b5ec94b45a
nlp = spacy.load("ru_core_news_lg")

In [24]:
def extract_entities_from_texts(texts):
    results = []
    for doc in nlp.pipe(texts, batch_size=50, n_process=-1):  # n_process=-1 использует все ядра
        entities = defaultdict(set)
        for ent in doc.ents:
            entities[ent.label_].add(ent.text)
        results.append(dict(entities))
    return results

final_df['entities'] = extract_entities_from_texts(final_df['text'].str.lower().tolist())

In [25]:
final_df

,text,tags,schema_name,table_name,entities
0,"1 1 1 Часть территории национального парка ""Ло...","[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_47923,"{'LOC': {'москвы', 'рф'}, 'ORG': {'минприроды'}}"
1,"1 1 1 Часть территории национального парка ""Ло...","[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_58710,"{'LOC': {'москвы', 'российской федерации'}}"
2,"2 2 2 Часть территории национального парка ""Ло...","[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_58710,{'LOC': {'москвы'}}
3,"3 3 3 Часть территории национального парка ""Ло...","[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_58710,{'LOC': {'москвы'}}
4,"4 4 4 Часть территории национального парка ""Ло...","[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_58710,{'LOC': {'москвы'}}
...,...,...,...,...,...
18419,996 996 982 20231117_110117.jpg 2023-11-17 00:...,"[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_47876,{}
18420,997 997 983 20231121_100442.jpg 2023-11-21 00:...,"[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_47876,{'PER': {'пип битцевский'}}
18421,998 998 984 20231121_095847.jpg 2023-11-21 00:...,"[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_47876,{'PER': {'пип битцевский'}}
18422,99 99 101 117 4.jpg 2023-11-16 00:00:00+00 13:...,"[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_47876,{}
18423,999 999 985 20231117_110043.jpg 2023-11-17 00:...,"[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_47876,{}

In [26]:
# визуализация
# text = final_df[5:6].reset_index()['text'].str.lower()[0]
text = final_df[100:101].reset_index()['text'][0]
doc = nlp(text)
displacy.render(doc, style="ent", jupyter=True)

# 3. Добавим labels и дообучим существующую NER-модель

In [27]:
# СЗАО - Северо-Западный административный округ
# САО - Северный административный округ
# СВАО - Северо-Восточный административный округ
# ЗАО - Западный административный округ
# ЦАО - Центральный административный округ
# ВАО - Восточный административный округ
# ЮЗАО - Юго-Западный административный округ
# ЮАО - Южный административный округ
# ЮВАО - Юго-Восточный административный округ
# ЗелАО - Зеленоградский административный округ
# ТиНАО - Троицкий и Новомосковский административные округа
# НАО - Новомосковский административный округ
# ТАО - Троицкий административный округ

In [28]:
result_df = df.copy()
moscow_districts = ['СЗАО', 'САО', 'СВАО', 'ЗАО', 'ЦАО', 'ВАО', 'ЮЗАО', 'ЮАО', 'ЮВАО', 'ЗелАО', 'ТиНАО', 'НАО', 'ТАО']
# Создаем регулярное выражение для поиска любого из значений
pattern = '|'.join(moscow_districts)
result_df = df[df['text'].str.contains(pattern, case=False, na=False)]

In [29]:
result_df

,text,tags,schema_name,table_name
72,"100 101 64 ООПТ регионального значения ""Памятн...","[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_54935
75,"102 103 3 ООПТ регионального значения ""Памятни...","[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_54935
118,"141 142 120 ООПТ регионального значения ""Фауни...","[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_54935
144,"31 31 138 ООПТ регионального значения ""Памятни...","[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_54935
215,"96 97 38 ООПТ регионального значения ""Природно...","[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_54935
...,...,...,...,...
18419,996 996 982 20231117_110117.jpg 2023-11-17 00:...,"[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_47876
18420,997 997 983 20231121_100442.jpg 2023-11-21 00:...,"[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_47876
18421,998 998 984 20231121_095847.jpg 2023-11-21 00:...,"[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_47876
18422,99 99 101 117 4.jpg 2023-11-16 00:00:00+00 13:...,"[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_47876
18423,999 999 985 20231117_110043.jpg 2023-11-17 00:...,"[МКА. Геоданные, 440 Особо охраняемые природны...",_46379,_47876

In [30]:
def find_all_positions(text, substring):
    """Находит все позиции вхождения подстроки в тексте"""
    positions = []
    start = 0
    while True:
        pos = text.find(substring, start)
        if pos == -1:
            break
        positions.append([pos, pos + len(substring)])
        start = pos + len(substring) # ищем следующее вхождение
    return positions
# Пример использования
text = "СЗАО и ВАО - это округа Москвы. СЗАО находится на северо-западе. СЗАО" 
substring = "СЗАО"
positions = find_all_positions(text, substring)
print(f"Подстрока '{substring}' найдена на позициях: {positions}")

Подстрока 'СЗАО' найдена на позициях: [[0, 4], [32, 36], [65, 69]]

In [31]:
def get_examples(df, entities_dict, nlp):
    all_annotated_examples = []
    texts = df['text'].tolist()
    for text in texts:
        example_for_text = []
        entities_for_text = []
        for entity in entities_dict:
            for value in entities_dict[entity]:
                # nonlocal positions
                positions = find_all_positions(text, value)
                for position in positions:
                    position.append(entity)
                    entities_for_text.append(tuple(position))
        
        doc = nlp(text)
        for ent in doc.ents:
            entities_for_text.append((ent.start_char, ent.end_char, ent.label_))
            
        if len(entities_for_text) > 0:
            example_for_text.insert(0, text)
            example_for_text.append({'entities': entities_for_text})
            all_annotated_examples.append(example_for_text)
    return all_annotated_examples

entities_values = {"DISTRICT":moscow_districts}
annotated_examples = get_examples(result_df[:100], entities_values, nlp)
print(annotated_examples)

[['100 101 64 ООПТ регионального значения "Памятник природы "Долина реки Чермянки от пр. Дежнева до устья" ППМ № 2119-ПП от 18.09.2024,ППМ № 1496-ПП от 11.09.2020 Памятники природы Утвержден ГБУ г. Москвы "Автомобильные дороги СВАО" https://docs7.online-sps.ru/cgi/online.cgi?from=228884-0&req=doc&rnd=JMzqYA&base=MLAW&n=246251#mUvXRTUQQIa3BB3w https://www.mos.ru/upload/content/files/020KDPPDolinarekiChermyankiotprDejnevadoystya(2).docx 15.55 15.5477 не совпадает с зонами режимов ООПТ (по координатам в ППМ - такая же геометрия) Иль С.А.: Проверен Мукаяров Е.А.: Внесено в соответствии с ППМ 2119 от 18.09.24', {'entities': [(224, 228, 'DISTRICT'), (225, 228, 'DISTRICT'), (70, 78, 'LOC'), (86, 93, 'PER'), (104, 117, 'ORG'), (195, 201, 'LOC'), (529, 537, 'PER'), (539, 561, 'PER'), (588, 591, 'ORG')]}], ['102 103 3 ООПТ регионального значения "Памятник природы "Пойма реки Городни от Братеевской ул. до реки Москвы" ППМ № 2406-ПП от 23.10.2024,ППМ № 1540-ПП от 16.09.2020 Памятники природы Утвержден ГБУ г. Москвы "Автомобильные дороги ЮАО" https://docs7.online-sps.ru/cgi/online.cgi?req=doc&base=MLAW&n=247272&cacheid=2983DE2D4027D2BFEFFDE73DD549A646&mode=splus&rnd=AfsqNg#AuNaWTUKGjEp2KKF1https://docs7.online-sps.ru/cgi/online.cgi?req=doc&base=MLAW&n=247272&cacheid=2983DE2D4027D2BFEFFDE73DD549A646&mode=splus&rnd=AfsqNg#AuNaWTUKGjEp2KKF1 https://www.mos.ru/upload/content/files/042KDPPPoimarekiGorodniotBrateevskoiyldorekiMoskvi.docx 10.87 10.8703 проверено Иль С.А.: Проверен Мукаяров Е.А.: внесено в соответствии с ППМ 2406 от 23.10.24', {'entities': [(231, 234, 'DISTRICT'), (68, 75, 'LOC'), (79, 94, 'LOC'), (103, 109, 'LOC'), (111, 124, 'ORG'), (185, 194, 'LOC'), (202, 208, 'LOC'), (657, 665, 'PER'), (667, 689, 'PER'), (716, 719, 'ORG')]}], ['141 142 120 ООПТ регионального значения "Фаунистический заказник "Братеевская пойма" ППМ № 2406-ПП от 23.10.2024,ППМ № 67-ПП от 06.02.2019,ППМ № 1540-ПП от 16.09.2020 Природный заказник Утвержден ГБУ г. Москвы "Автомобильные дороги ЮАО" https://docs7.online-sps.ru/cgi/online.cgi?from=206807-0&req=doc&rnd=AfsqNg&base=MLAW&n=247272#qmetWTUewzE4eqs93 https://www.mos.ru/upload/content/files/010KDFZBrateevskayapoima.docx 226.04 226.0406 Иль С.А.: Проверен Мукаяров Е.А.: внесено в соответствии с ППМ 2406 от 23.10.24', {'entities': [(232, 235, 'DISTRICT'), (66, 83, 'LOC'), (85, 98, 'ORG'), (186, 195, 'LOC'), (203, 209, 'LOC'), (446, 468, 'PER'), (495, 498, 'ORG')]}], ['31 31 138 ООПТ регионального значения "Памятник природы "Устье реки Лихоборки" ППМ № 2119-ПП от 18.09.2024,ППМ № 1496-ПП от 11.09.2020 Памятники природы Утвержден ГБУ г. Москвы "Автомобильные дороги СВАО" https://docs7.online-sps.ru/cgi/online.cgi?req=doc&base=MLAW&n=246251&cacheid=3187E19D12CA3284889FF10C119827F3&mode=splus&rnd=svztFw#NewERTU6F9Il4eeD1 https://www.mos.ru/upload/content/files/058KDPPYsterekiLihoborki.docx 2.66 2.6624 проверено Иль С.А.: Проверен Мукаяров Е.А.: Внесено в соответствии с ППМ 2119 от 18.09.24', {'entities': [(199, 203, 'DISTRICT'), (200, 203, 'DISTRICT'), (79, 92, 'ORG'), (170, 176, 'LOC'), (448, 456, 'PER'), (458, 480, 'PER'), (507, 510, 'ORG')]}], ['96 97 38 ООПТ регионального значения "Природно-исторический парк "Останкино" ППМ № 2119-ПП от 18.09.2024,ППМ № 2809-ПП от 13.12.2022,ППМ № 1012 от 29.12.1998,ППМ № 382-ПП от 11.05.2010,ППМ № 208-ПП от 14.04.2015,ППМ № 593-ПП от 21.09.2016,ППМ № 70-ПП от 22.02.2017,ППМ № 1496-ПП от 11.09.2020 Природно-исторический парк Утвержден ГБУ г.Москвы "Автомобильные дороги СВАО", ГБУК г.Москвы "Государственный дворцово-парковый музей-заповедник "Останкино и Кусково", ГАУК г.Москвы "Парк культуры и отдыха "Бабушкинский" https://docs7.online-sps.ru/cgi/online.cgi?req=doc&base=MLAW&n=228884&cacheid=50EB8540AB4272EE720E236FD571380E&mode=splus&rnd=fLrAdA#k1h1owTGQVZvnkTW1 https://www.mos.ru/upload/content/files/007KDPIPOstankino.docx 736.01 736.013 несоответсвие текстовой и графической частей ППМ: зона ИК-4 в ППМ - 377,82 га, по графике - 377,85 га зона РЦ-3 в ППМ - 2,11 га, по графике - 2,08 га зона АХ-9 в ППМ - 0,8 га, по графике - 1,33 га зона АХ-10 в ППМ - 0,23 га, по графике - 0,8 га зона АХ-8 в ППМ - 1,37 га, нет в графической части зона АХ-11 в ППМ - 0,1 га, дублируется в графике! (0,23 га и 0,097 га) зоны ОКС 13 и 67 были упразднены, но в ППМ не внесли изменения не найдены зоны ОКС 33, 34 Иль С.А.: Проверен Мукаяров Е.А.: Внесены изменения в соответствии с ППМ 2119 от 18.09.24', {'entities': [(365, 369, 'DISTRICT'), (366, 369, 'DISTRICT'), (66, 75, 'ORG'), (320, 329, 'LOC'), (336, 342, 'LOC'), (372, 376, 'ORG'), (379, 385, 'LOC'), (439, 448, 'LOC'), (451, 458, 'LOC'), (461, 465, 'ORG'), (468, 474, 'LOC'), (500, 512, 'ORG'), (788, 791, 'ORG'), (798, 802, 'ORG'), (898, 902, 'ORG'), (993, 997, 'ORG'), (1115, 1118, 'ORG'), (1149, 1152, 'ORG'), (1189, 1192, 'ORG'), (1210, 1232, 'PER'), (1269, 1272, 'ORG')]}], ['99 100 17 ООПТ регионального значения "Памятник природы "Родник на левобережном склоне долины реки Яузы в Старом Свиблово" ППМ № 2119 от 18.09.2024,ППМ № 2809-ПП от 13.12.2022,ППМ № 1496-ПП от 11.09.2020 Памятники природы Утвержден ГБУ г. Москвы "Автомобильные дороги СВАО" https://docs7.online-sps.ru/cgi/online.cgi?req=doc&base=MLAW&n=246251&cacheid=3187E19D12CA3284889FF10C119827F3&mode=splus&rnd=svztFw#NewERTU6F9Il4eeD1 https://www.mos.ru/upload/content/files/050KDPPRodniknalevoberejnomsklonedolinirekiYayzivStaromSviblovo.docx 0.6 0.6015 проверено Иль С.А.: Проверен Мукаяров Е.А.: Внесено в соответствии с ППМ 2119 от 18.09.24', {'entities': [(268, 272, 'DISTRICT'), (269, 272, 'DISTRICT'), (99, 103, 'LOC'), (106, 121, 'LOC'), (239, 245, 'LOC'), (555, 563, 'PER'), (565, 587, 'PER'), (614, 617, 'ORG')]}], ['100 103 Памятник природы "Исток Реки Очаковки" 026 1991-10-17 00:00:00+00 Памятник природы «Долина реки Очаковки в Теплом Стане» - особо охраняемая природная территория, представляющая собой уникальный природный объект, имеющий эстетическое, рекреационное и эколого-просветительского значение. Основным назначением и целями памятника природы являются сохранение уникальных природных объектов и природных сообществ, обеспечение условий для прогулок и отдыха в природном окружении. 1.17 ЮЗАО Тёплый Стан (ЮЗАО) 253 249 Постановление Правительства Москвы от 29.09.2020 № 1620-ПП "Об особо охраняемой природной территории регионального значения "Ландшафтный заказник "Теплый стан" и памятниках природы, расположенных в ее границах", Решение Президиума Московского городского Совета народных депутатов от 17.10.1991 № 201 "О государственных памятниках природы местного значения в городе Москве" отпрепарированный склоновый структурно-денудационный выступ, сложенный дочетвертичными породами Префектура ЮЗАО, ГБУ "Автомобильные Дороги ЮЗАО", Департамент природопользования и охраны окружающей среды города Москвы, ГПБУ "Государственный Природоохранный Центр" Lathyrus vernus, Campanula persicifolia, Campanula trachelium, Pulmonaria obscura, Myosotis palustris, Polygonatum multiflorum Урбанозем гумусированный слабо-среднемощный на моренно или покровном суглинке Окружен густонаселенными жилыми кварталами и территория имеет высокую посещаемость Среди основных антропогенных воздействий отмечено значительное развитие тропиночной сети и поросль малоценных пород. В целом рекреационная нагрузка на территорию весьма велика 77:06:0007002:1867, 77:06:0007003:82, 77:06:0007002:2265 103', {'entities': [(486, 489, 'DISTRICT'), (504, 507, 'DISTRICT'), (998, 1001, 'DISTRICT'), (1030, 1033, 'DISTRICT'), (485, 489, 'DISTRICT'), (503, 507, 'DISTRICT'), (997, 1001, 'DISTRICT'), (1029, 1033, 'DISTRICT'), (26, 45, 'ORG'), (104, 112, 'LOC'), (115, 127, 'LOC'), (485, 489, 'LOC'), (490, 508, 'LOC'), (545, 551, 'LOC'), (748, 770, 'ORG'), (771, 796, 'ORG'), (882, 888, 'LOC'), (986, 996, 'LOC'), (997, 1001, 'ORG'), (1003, 1034, 'ORG'), (1036, 1092, 'ORG'), (1100, 1106, 'LOC'), (1108, 1169, 'ORG'), (1216, 1234, 'ORG'), (1280, 1289, 'PER')]}], ['10 10 Природно-исторический парк "Москворецкий" 006 1998-12-29 00:00:00+00 Природно-исторический парк «Москворецкий» - особо охраняемая природная территория регионального значения, имеющая природоохранное, историко-культурное, просветительское, рекреационное и познавательное значение как особо ценный для города Москвы природный комплекс и памятник отечественной истории и культуры, на которой, в том числе, представлены объекты живой или неживой природы (уникальные, редкие, хорошо сохранившиеся). Использование особо охраняемой природной территории регионального значения «Природно-исторический парк «Москворецкий» допускается в культурно-просветительских, рекреационных, физкультурно-оздоровительных и спортивных целях. 3440.49 ЗАО, СЗАО Крылатское (ЗАО), Кунцево (ЗАО), Митино (СЗАО), Покровское-Стрешнево (СЗАО), Проспект Вернадского (ЗАО), Строгино (СЗАО), Филёвский парк (ЗАО), Фили-Давыдково (ЗАО), Хорошёво-Мневники (СЗАО), Щукино (СЗАО), Южное Тушино (СЗАО) 216 115 Постановление Правительства Москвы от 19.11.2020 № 2013-ПП "Об особо охраняемой природной территории регионального значения «природно-исторический парк "Москворецкий" и памятниках природы, расположенных в ее границах", Постановление Правительства Москвы от 29.12.1998 N 1012 "О проектных предложениях по установлению границ особо охраняемых природных территорий: природно-исторического парка "Москворецкий" и природно-исторического парка "Останкино" аккумулятивный грядово-холмистый конечно-моренный рельеф московского времени, аккумулятивный полого-волнистый моренный рельеф, аккумулятивный полого-волнистый рельеф основной морены московского времени, аллювиальные первая и вторая надпойменные террасы валдайского возраста, пойменная терраса голоценового возраста, эрозионно-аккумулятивные флювиогляциальные равнины времен московского оледенения Департамент жилищно-коммунального хозяйства города Москвы, Департамент культуры города Москвы, Префектура ЗАО, Префектура СЗАО, ГБУ "Автомобильные дороги", ГБУ "Мосприрода" , ГБУ "Автомобильные Дороги ЗАО" , ГБУ "Автомобильные Дороги СЗАО", Департамент природопользования и охраны окружающей среды города Москвы, ГПБУ "Государственный Природоохранный Центр" Nymphaea candida, Caltha palustris, Trollius europaeus, Bistorta major, Coccyganthe flos-cuculi, Steris viscaria, Dianthus fischeri, Lathyrus vernus, Fragaria viridis, Campanula patula, Campanula persicifolia, Campanula rotundifolia, Pulmonaria obscura, Polygonatum odoratum Neomys fodiens, Erinaceus europaeus, Nyctalus noctula, Mustela nivalis, Lepus europaeus, Lepus timidus, Anas querquedula, Anas clypeata, Aythya ferina, Aythya fuligula, Accipiter gentilis, Accipiter nisus, Falco tinnunculus, Porzana porzana, Crex crex, Gallinula chloropus, Fulica atra, Larus ridibundus, Larus canus, Sterna hirundo, Cuculus canorus, Asio otus, Strix aluco, Dendrocopos leucotos, Riparia riparia, Alauda arvensis, Motacilla flava, Lanius collurio, Locustella fluviatilis, Acrocephalus arundinaceus, Saxicola rubetra, Aegithalos caudatus, Natrix natrix, Rana temporaria, Rana arvalis, Leuciscus leuciscus, Leuciscus cephalus, Tinca tinca, Silurus glanis, Sympetrum pedemontanum, Tettigonia cantans, Decticus verrucivorus, Metrioptera brachyptera, Metrioptera bicolor, Prionus coriarius, Andrena hattorfiana, Anthidium manicatum, Anthidium punctatum, Hyponephele lycaon, Apatura ilia, Limenitis populi, Brenthis ino, Lycaena alciphron, Glaucopsyche alexis, Endromis versicolora, Aglia tau, Hemaris fuciformis Урбанозем гумусированный средне-сильномощный на флювиогляциальных песках и супесях, Дерново-средне-сильноурбоподзолистая слабо-средненарушенная на моренном и покровном суглинке, Слабо-среднедерново-урбоподзолистая на флювиогляциальных песках и супесях, Аллювиальные дерновые, луговые на аллювиальных. слоистых песчано-супесчаных отложениях, Индустризем малогумусный маломощный на насыпном и привозном грунте, Индустризем слабогумусированный мало-сильномощный на насыпном грунте или культурном слое, Почвы кладбищ (некроземы), nan, Индустризем малогумусный мало-среднемощный на культурном слое и покровном суглинке, Индустризем слабогумусированный мало-среднемощный на насыпном и привозном грунте , Урбанозем гумусированный слабо-среднемощный на моренно или покровном суглинке, Урбанозем гумусированный средне-сильномощный на культурном слое и покровном суглинке, Урбанозем гумусированный слабо-среднемощный, Слабо-среднедерново-слабо-средне-сильноурбоподзолистая на двучленных отложениях "Артиллерийский ДОТ Московской линии обороны, 1941 г.", "Главный дом (деревянный)", XVIII в., Дот, 1941 г., Загородная усадьба, XVIII в., Комплекс сооружений канала им. Москвы, 19321937 гг., Надгробие Николая Григорьевича Гурьева (1868 1905), "Парк", XVIII в., Усадьба "ТроицкоеЛыково", Усадьба "ФилиКунцево", "Флигель", XVIII в., "Храм Успения Пресвятой Богородицы в усадьбе Троице–Лыково, 1850–е гг., 1900–е гг., архитектор С.Ф.Кулагин", "Церковь в селе Крылатском", XVIII в., "Церковь Покрова в Филях", 1693–1694 гг., "Церковь Троицы", 1693 г., "Церковь Троицы", 1698 – 1704 гг., Шлюз 1, арх. Белдовский, Шлюз 2, арх. А.Л.Пастернак, Шлюз 4, арх. Г.Г.Вегман, А.Л.Пастернак, Шлюз 5, арх. Д.Б.Савицкий, Шлюз 78, арх. В.Ф.Кринский Нарушенность территорий невелика. На ООПТ присутствуют значительные по площади лесные массивы (два Серебряноборских и Фили-Кунцевский) и небольшие лесные островки (на Крылатских холмах и в Крылатской пойме), обширные луга и небольшие луговины, представляющие естественные биотопы Помимо постоянно действующих факторов антропогенного воздействия (фоновое загрязнение атмосферы, длительное хозяйственное использование и интенсивная урбанизация прилегающих территорий), можно выделить несколько локальных негативных факторов, наиболее значимых для данной территории. К ним относятся: - Выбросы автотранспорта, оказывающие значительное влияние на загрязнение атмосферного воздуха, а воздушный перенос способствует поступлению загрязняющих веществ в почвенный покров. Также при передвижении автотранспорта по автомобильным дорогам с различной степенью интенсивности движения увеличивается воздействие негативных физических факторов. Территория преобразована техногенной и антропогенной деятельностью объектов гидротехнических сооружений канала им. Москвы, рекреационным и спортивно-рекреационным освоением, антропогенной нагрузкой со стороны МКАД. 77:08:0002022:2, 77:08:0000000:3350, 77:08:0000000:6167, 77:08:0002022:4011, 77:08:0002023:2065, 77:08:0009001:9, 77:08:0009001:3924, 77:08:0006013:11, 77:08:0009001:54, 77:08:0007006:9, 77:08:0005006:19, 77:08:0005001:37, 77:08:0005001:1702, 77:08:0006007:3038, 77:08:0005010:5599, 77:08:0005010:11, 77:08:0005010:1000, 77:08:0005009:2754, 77:08:0005007:56, 77:08:0015001:3628, 77:08:0015001:1716, 77:08:0008001:3937, 77:08:0006012:16, 77:08:0005010:44, 77:08:0005009:43, 77:08:0005010:46, 77:08:0006007:29, 77:08:0015001:1770, 77:08:0005008:1296, 77:08:0005009:2755, 77:08:0005010:1522, 77:08:0006007:3047, 77:08:0015001:1717, 77:08:0012003:4141, 77:08:0010001:9017, 77:08:0010001:14, 77:08:0010001:1000, 77:08:0010016:1570, 77:08:0010016:1217, 77:08:0010016:3, 77:08:0010001:59, 77:08:0010016:2, 77:08:0010001:15, 77:08:0010001:9804, 77:08:0010016:1238, 77:08:0013001:117, 77:08:0013001:12, 77:08:0000000:6831, 77:08:0013002:6, 77:08:0013011:1540, 77:08:0013011:1506, 77:08:0013011:1001, 77:08:0013002:1101, 77:08:0013009:1000, 77:08:0013011:2, 77:08:0013011:1875, 77:08:0005001:1945, 77:08:0005001:1924, 77:08:0005005:79, 77:08:0005006:43, 77:08:0009021:2570, 77:08:0009021:1185, 77:07:0001003:1889, 77:07:0000000:6100, 77:07:0001003:1003, 77:07:0001003:1001, 77:07:0001003:1006, 77:07:0001003:1894, 77:07:0001003:2275, 77:07:0001003:2279, 77:07:0001003:2281, 77:07:0001004:1008, 77:07:0001004:1007, 77:07:0001004:1006, 77:07:0001004:2418, 77:07:0001004:2203, 77:07:0001004:2738, 77:07:0001004:2763, 77:07:0001004:2743, 77:08:0013011:1559, 77:07:0003003:3854, 77:07:0001003:1876, 77:07:0001003:1891, 77:07:0001003:36, 77:07:0001003:16, 77:07:0001003:1890, 77:00:0000000:73928, 77:08:0013011:3, 77:08:0013011:1, 77:08:0013011:1539, 77:08:0013011:1558, 77:07:0001003:22, 77:07:0001003:13, 77:08:0013014:2330, 77:08:0013014:1691, 77:07:0001004:7, 77:07:0001004:5, 77:07:0001004:42, 77:07:0001004:2202, 77:07:0001004:3105, 77:07:0001004:3101, 77:07:0001004:3098, 77:07:0001003:1005, 77:07:0001003:1004, 77:07:0001004:2744, 77:07:0001004:2742, 77:07:0001004:2737, 77:07:0001004:2697, 77:07:0001004:2426, 77:07:0001004:2425, 77:07:0001004:2424, 77:07:0001004:2423, 77:07:0001004:2422, 77:07:0001004:2421, 77:07:0001004:2226, 77:07:0001004:1009, 77:07:0001004:1005, 77:07:0001004:1004, 77:07:0001004:1003, 77:07:0001004:1002, 77:07:0001003:31, 77:07:0001003:2280, 77:07:0001003:2276, 77:07:0001003:1860, 77:07:0001003:1792, 77:07:0000000:6099, 77:07:0001003:2277, 77:07:0001003:1007, 77:07:0001004:6, 77:07:0001004:41, 77:07:0001004:32, 77:07:0001003:15, 77:07:0001004:37, 77:07:0001003:18, 77:07:0001003:30, 77:07:0001004:33, 77:07:0001004:3204, 77:07:0001004:4, 77:07:0001004:15, 77:07:0001004:1, 77:07:0001003:9, 77:08:0006015:20, 77:08:0006011:37, 77:08:0007003:22, 77:08:0006011:3007, 77:07:0003002:1909, 77:07:0003002:19, 77:07:0003002:1890, 77:07:0003002:1889, 77:07:0003002:1446, 77:07:0003002:1000, 77:07:0001001:12717, 77:07:0001001:9309, 77:07:0001001:1002, 77:07:0003002:14, 77:07:0003002:16, 77:07:0003002:18, 77:07:0003002:20, 77:07:0003002:21, 77:07:0003002:22, 77:07:0003002:23, 77:07:0003002:24, 77:07:0003002:25, 77:07:0003003:20, 77:07:0003001:17, 77:07:0003002:15, 77:07:0001001:42, 77:07:0003002:1577, 77:07:0003002:13, 77:07:0003002:10, 77:07:0003001:31, 77:07:0001001:11880, 77:07:0001001:8744, 77:07:0003002:1575, 77:07:0001001:8748, 77:07:0001001:74, 77:07:0001001:72, 77:07:0001001:29, 77:08:0013001:164, 77:08:0013001:15, 77:07:0001003:32, 77:08:0013011:5, 77:07:0001001:71, 77:07:0001001:1, 77:08:0008009:1000, 77:08:0008012:4, 77:08:0008010:3, 77:08:0008010:24, 77:08:0008010:23, 77:08:0008010:2, 77:08:0008010:17, 77:08:0008009:39, 77:08:0008010:1390, 77:08:0008010:1076, 77:08:0008010:1065, 77:08:0008010:1066, 77:08:0008010:1063, 77:08:0008010:1001, 77:08:0008009:5998, 77:08:0008009:5626, 77:08:0008012:1007, 77:08:0008010:4, 77:08:0008010:22, 77:08:0008001:4, 77:08:0008009:48, 77:08:0008009:47, 77:08:0008010:9, 77:08:0008001:67, 77:08:0008009:54, 77:08:0008010:1069, 77:08:0008009:5997, 77:08:0008010:1000, 77:08:0008010:1004, 77:08:0009021:2568, 77:08:0009021:1001, 77:08:0009021:1230, 77:08:0002017:1916, 77:08:0002016:9354, 77:08:0002016:8268, 77:08:0002016:4576, 77:08:0000000:1042, 77:08:0002016:4451, 77:08:0002001:292, 77:08:0000000:7073, 77:08:0002014:2354, 77:08:0002014:2356, 77:08:0002014:2357, 77:08:0002014:2355, 77:08:0002014:2353, 77:08:0000000:3315, 77:08:0000000:7247, 77:08:0002016:4450, 77:08:0002016:7077, 77:08:0002016:7075, 77:08:0002014:2814, 77:07:0003001:28, 77:07:0003001:2636, 77:07:0003001:23, 77:07:0003001:25, 77:07:0003001:27, 77:07:0000000:13622, 77:07:0003001:22, 77:07:0003001:34, 77:07:0003001:1001, 77:07:0003003:21, 77:07:0003001:36, 77:07:0003001:35, 77:07:0003001:32, 77:07:0003001:29, 77:07:0003001:26, 77:07:0003001:24, 77:07:0003001:1000, 77:07:0003001:2633, 77:07:0003001:30, 77:08:0009021:1000, 77:08:0009021:1007, 77:08:0013013:59, 77:08:0008010:1064, 77:08:0008010:1003, 77:08:0010016:1253, 77:08:0010016:1255, 77:08:0013012:1703, 77:08:0010001:62, 77:08:0010001:39, 77:08:0010001:25, 77:08:0008010:1, 77:08:0009021:32, 77:08:0008010:1068, 77:08:0013013:1016, 77:08:0013001:77, 77:08:0013001:27, 77:08:0013011:4, 77:08:0013009:1002, 77:08:0013002:9, 77:08:0013010:1795, 77:08:0002016:8273, 77:08:0002016:8267, 77:08:0002016:8266, 77:08:0002016:8265, 77:08:0002016:8261, 77:08:0002016:7080, 77:08:0002016:7076, 77:08:0002016:4453, 77:08:0002016:4452, 77:08:0002014:2813, 77:08:0002016:8264, 77:08:0008001:69, 77:08:0008001:66, 77:08:0008001:36, 77:08:0008001:1009, 77:08:0008001:1006, 77:08:0008001:1000, 77:08:0008001:68, 77:08:0015001:44, 77:08:0005010:22, 77:08:0008001:50, 77:08:0015001:23, 77:08:0005010:8, 77:08:0015001:1001, 77:07:0005008:101, 77:07:0005010:16, 77:07:0005010:1

In [32]:
def resolve_overlapping_entities(training_sample):
    """
    Удаляет все пересекающиеся сущности, оставляя только непересекающиеся.
    При конфликте выбирает сущность с наибольшей длиной.
    """
    text, annotations = training_sample
    entities = annotations.get('entities', [])
    
    if not entities:
        return training_sample
    
    # Удаляем дубликаты
    unique_entities = list(set(tuple(entity) for entity in entities))
    
    # Сортируем по длине (от самой длинной к самой короткой)
    sorted_by_length = sorted(unique_entities, 
                             key=lambda x: (x[1] - x[0]), 
                             reverse=True)
    
    result_entities = []
    used_positions = set()
    
    for entity in sorted_by_length:
        start, end, label = entity
        entity_positions = set(range(start, end))
        
        # Проверяем, пересекается ли с уже добавленными сущностями
        if not entity_positions.intersection(used_positions):
            result_entities.append(entity)
            used_positions.update(entity_positions)
    
    # Сортируем по начальной позиции
    result_entities.sort(key=lambda x: x[0])
    
    return [text, {'entities': result_entities}]

In [33]:
resolved_annotated_examples = []
for example in annotated_examples:
    resolved_example = resolve_overlapping_entities(example)
    resolved_annotated_examples.append(resolved_example)
print(resolved_annotated_examples)

[['100 101 64 ООПТ регионального значения "Памятник природы "Долина реки Чермянки от пр. Дежнева до устья" ППМ № 2119-ПП от 18.09.2024,ППМ № 1496-ПП от 11.09.2020 Памятники природы Утвержден ГБУ г. Москвы "Автомобильные дороги СВАО" https://docs7.online-sps.ru/cgi/online.cgi?from=228884-0&req=doc&rnd=JMzqYA&base=MLAW&n=246251#mUvXRTUQQIa3BB3w https://www.mos.ru/upload/content/files/020KDPPDolinarekiChermyankiotprDejnevadoystya(2).docx 15.55 15.5477 не совпадает с зонами режимов ООПТ (по координатам в ППМ - такая же геометрия) Иль С.А.: Проверен Мукаяров Е.А.: Внесено в соответствии с ППМ 2119 от 18.09.24', {'entities': [(70, 78, 'LOC'), (86, 93, 'PER'), (104, 117, 'ORG'), (195, 201, 'LOC'), (224, 228, 'DISTRICT'), (529, 537, 'PER'), (539, 561, 'PER'), (588, 591, 'ORG')]}], ['102 103 3 ООПТ регионального значения "Памятник природы "Пойма реки Городни от Братеевской ул. до реки Москвы" ППМ № 2406-ПП от 23.10.2024,ППМ № 1540-ПП от 16.09.2020 Памятники природы Утвержден ГБУ г. Москвы "Автомобильные дороги ЮАО" https://docs7.online-sps.ru/cgi/online.cgi?req=doc&base=MLAW&n=247272&cacheid=2983DE2D4027D2BFEFFDE73DD549A646&mode=splus&rnd=AfsqNg#AuNaWTUKGjEp2KKF1https://docs7.online-sps.ru/cgi/online.cgi?req=doc&base=MLAW&n=247272&cacheid=2983DE2D4027D2BFEFFDE73DD549A646&mode=splus&rnd=AfsqNg#AuNaWTUKGjEp2KKF1 https://www.mos.ru/upload/content/files/042KDPPPoimarekiGorodniotBrateevskoiyldorekiMoskvi.docx 10.87 10.8703 проверено Иль С.А.: Проверен Мукаяров Е.А.: внесено в соответствии с ППМ 2406 от 23.10.24', {'entities': [(68, 75, 'LOC'), (79, 94, 'LOC'), (103, 109, 'LOC'), (111, 124, 'ORG'), (185, 194, 'LOC'), (202, 208, 'LOC'), (231, 234, 'DISTRICT'), (657, 665, 'PER'), (667, 689, 'PER'), (716, 719, 'ORG')]}], ['141 142 120 ООПТ регионального значения "Фаунистический заказник "Братеевская пойма" ППМ № 2406-ПП от 23.10.2024,ППМ № 67-ПП от 06.02.2019,ППМ № 1540-ПП от 16.09.2020 Природный заказник Утвержден ГБУ г. Москвы "Автомобильные дороги ЮАО" https://docs7.online-sps.ru/cgi/online.cgi?from=206807-0&req=doc&rnd=AfsqNg&base=MLAW&n=247272#qmetWTUewzE4eqs93 https://www.mos.ru/upload/content/files/010KDFZBrateevskayapoima.docx 226.04 226.0406 Иль С.А.: Проверен Мукаяров Е.А.: внесено в соответствии с ППМ 2406 от 23.10.24', {'entities': [(66, 83, 'LOC'), (85, 98, 'ORG'), (186, 195, 'LOC'), (203, 209, 'LOC'), (232, 235, 'DISTRICT'), (446, 468, 'PER'), (495, 498, 'ORG')]}], ['31 31 138 ООПТ регионального значения "Памятник природы "Устье реки Лихоборки" ППМ № 2119-ПП от 18.09.2024,ППМ № 1496-ПП от 11.09.2020 Памятники природы Утвержден ГБУ г. Москвы "Автомобильные дороги СВАО" https://docs7.online-sps.ru/cgi/online.cgi?req=doc&base=MLAW&n=246251&cacheid=3187E19D12CA3284889FF10C119827F3&mode=splus&rnd=svztFw#NewERTU6F9Il4eeD1 https://www.mos.ru/upload/content/files/058KDPPYsterekiLihoborki.docx 2.66 2.6624 проверено Иль С.А.: Проверен Мукаяров Е.А.: Внесено в соответствии с ППМ 2119 от 18.09.24', {'entities': [(79, 92, 'ORG'), (170, 176, 'LOC'), (199, 203, 'DISTRICT'), (448, 456, 'PER'), (458, 480, 'PER'), (507, 510, 'ORG')]}], ['96 97 38 ООПТ регионального значения "Природно-исторический парк "Останкино" ППМ № 2119-ПП от 18.09.2024,ППМ № 2809-ПП от 13.12.2022,ППМ № 1012 от 29.12.1998,ППМ № 382-ПП от 11.05.2010,ППМ № 208-ПП от 14.04.2015,ППМ № 593-ПП от 21.09.2016,ППМ № 70-ПП от 22.02.2017,ППМ № 1496-ПП от 11.09.2020 Природно-исторический парк Утвержден ГБУ г.Москвы "Автомобильные дороги СВАО", ГБУК г.Москвы "Государственный дворцово-парковый музей-заповедник "Останкино и Кусково", ГАУК г.Москвы "Парк культуры и отдыха "Бабушкинский" https://docs7.online-sps.ru/cgi/online.cgi?req=doc&base=MLAW&n=228884&cacheid=50EB8540AB4272EE720E236FD571380E&mode=splus&rnd=fLrAdA#k1h1owTGQVZvnkTW1 https://www.mos.ru/upload/content/files/007KDPIPOstankino.docx 736.01 736.013 несоответсвие текстовой и графической частей ППМ: зона ИК-4 в ППМ - 377,82 га, по графике - 377,85 га зона РЦ-3 в ППМ - 2,11 га, по графике - 2,08 га зона АХ-9 в ППМ - 0,8 га, по графике - 1,33 га зона АХ-10 в ППМ - 0,23 га, по графике - 0,8 га зона АХ-8 в ППМ - 1,37 га, нет в графической части зона АХ-11 в ППМ - 0,1 га, дублируется в графике! (0,23 га и 0,097 га) зоны ОКС 13 и 67 были упразднены, но в ППМ не внесли изменения не найдены зоны ОКС 33, 34 Иль С.А.: Проверен Мукаяров Е.А.: Внесены изменения в соответствии с ППМ 2119 от 18.09.24', {'entities': [(66, 75, 'ORG'), (320, 329, 'LOC'), (336, 342, 'LOC'), (365, 369, 'DISTRICT'), (372, 376, 'ORG'), (379, 385, 'LOC'), (439, 448, 'LOC'), (451, 458, 'LOC'), (461, 465, 'ORG'), (468, 474, 'LOC'), (500, 512, 'ORG'), (788, 791, 'ORG'), (798, 802, 'ORG'), (898, 902, 'ORG'), (993, 997, 'ORG'), (1115, 1118, 'ORG'), (1149, 1152, 'ORG'), (1189, 1192, 'ORG'), (1210, 1232, 'PER'), (1269, 1272, 'ORG')]}], ['99 100 17 ООПТ регионального значения "Памятник природы "Родник на левобережном склоне долины реки Яузы в Старом Свиблово" ППМ № 2119 от 18.09.2024,ППМ № 2809-ПП от 13.12.2022,ППМ № 1496-ПП от 11.09.2020 Памятники природы Утвержден ГБУ г. Москвы "Автомобильные дороги СВАО" https://docs7.online-sps.ru/cgi/online.cgi?req=doc&base=MLAW&n=246251&cacheid=3187E19D12CA3284889FF10C119827F3&mode=splus&rnd=svztFw#NewERTU6F9Il4eeD1 https://www.mos.ru/upload/content/files/050KDPPRodniknalevoberejnomsklonedolinirekiYayzivStaromSviblovo.docx 0.6 0.6015 проверено Иль С.А.: Проверен Мукаяров Е.А.: Внесено в соответствии с ППМ 2119 от 18.09.24', {'entities': [(99, 103, 'LOC'), (106, 121, 'LOC'), (239, 245, 'LOC'), (268, 272, 'DISTRICT'), (555, 563, 'PER'), (565, 587, 'PER'), (614, 617, 'ORG')]}], ['100 103 Памятник природы "Исток Реки Очаковки" 026 1991-10-17 00:00:00+00 Памятник природы «Долина реки Очаковки в Теплом Стане» - особо охраняемая природная территория, представляющая собой уникальный природный объект, имеющий эстетическое, рекреационное и эколого-просветительского значение. Основным назначением и целями памятника природы являются сохранение уникальных природных объектов и природных сообществ, обеспечение условий для прогулок и отдыха в природном окружении. 1.17 ЮЗАО Тёплый Стан (ЮЗАО) 253 249 Постановление Правительства Москвы от 29.09.2020 № 1620-ПП "Об особо охраняемой природной территории регионального значения "Ландшафтный заказник "Теплый стан" и памятниках природы, расположенных в ее границах", Решение Президиума Московского городского Совета народных депутатов от 17.10.1991 № 201 "О государственных памятниках природы местного значения в городе Москве" отпрепарированный склоновый структурно-денудационный выступ, сложенный дочетвертичными породами Префектура ЮЗАО, ГБУ "Автомобильные Дороги ЮЗАО", Департамент природопользования и охраны окружающей среды города Москвы, ГПБУ "Государственный Природоохранный Центр" Lathyrus vernus, Campanula persicifolia, Campanula trachelium, Pulmonaria obscura, Myosotis palustris, Polygonatum multiflorum Урбанозем гумусированный слабо-среднемощный на моренно или покровном суглинке Окружен густонаселенными жилыми кварталами и территория имеет высокую посещаемость Среди основных антропогенных воздействий отмечено значительное развитие тропиночной сети и поросль малоценных пород. В целом рекреационная нагрузка на территорию весьма велика 77:06:0007002:1867, 77:06:0007003:82, 77:06:0007002:2265 103', {'entities': [(26, 45, 'ORG'), (104, 112, 'LOC'), (115, 127, 'LOC'), (485, 489, 'DISTRICT'), (490, 508, 'LOC'), (545, 551, 'LOC'), (748, 770, 'ORG'), (771, 796, 'ORG'), (882, 888, 'LOC'), (986, 996, 'LOC'), (997, 1001, 'ORG'), (1003, 1034, 'ORG'), (1036, 1092, 'ORG'), (1100, 1106, 'LOC'), (1108, 1169, 'ORG'), (1216, 1234, 'ORG'), (1280, 1289, 'PER')]}], ['10 10 Природно-исторический парк "Москворецкий" 006 1998-12-29 00:00:00+00 Природно-исторический парк «Москворецкий» - особо охраняемая природная территория регионального значения, имеющая природоохранное, историко-культурное, просветительское, рекреационное и познавательное значение как особо ценный для города Москвы природный комплекс и памятник отечественной истории и культуры, на которой, в том числе, представлены объекты живой или неживой природы (уникальные, редкие, хорошо сохранившиеся). Использование особо охраняемой природной территории регионального значения «Природно-исторический парк «Москворецкий» допускается в культурно-просветительских, рекреационных, физкультурно-оздоровительных и спортивных целях. 3440.49 ЗАО, СЗАО Крылатское (ЗАО), Кунцево (ЗАО), Митино (СЗАО), Покровское-Стрешнево (СЗАО), Проспект Вернадского (ЗАО), Строгино (СЗАО), Филёвский парк (ЗАО), Фили-Давыдково (ЗАО), Хорошёво-Мневники (СЗАО), Щукино (СЗАО), Южное Тушино (СЗАО) 216 115 Постановление Правительства Москвы от 19.11.2020 № 2013-ПП "Об особо охраняемой природной территории регионального значения «природно-исторический парк "Москворецкий" и памятниках природы, расположенных в ее границах", Постановление Правительства Москвы от 29.12.1998 N 1012 "О проектных предложениях по установлению границ особо охраняемых природных территорий: природно-исторического парка "Москворецкий" и природно-исторического парка "Останкино" аккумулятивный грядово-холмистый конечно-моренный рельеф московского времени, аккумулятивный полого-волнистый моренный рельеф, аккумулятивный полого-волнистый рельеф основной морены московского времени, аллювиальные первая и вторая надпойменные террасы валдайского возраста, пойменная терраса голоценового возраста, эрозионно-аккумулятивные флювиогляциальные равнины времен московского оледенения Департамент жилищно-коммунального хозяйства города Москвы, Департамент культуры города Москвы, Префектура ЗАО, Префектура СЗАО, ГБУ "Автомобильные дороги", ГБУ "Мосприрода" , ГБУ "Автомобильные Дороги ЗАО" , ГБУ "Автомобильные Дороги СЗАО", Департамент природопользования и охраны окружающей среды города Москвы, ГПБУ "Государственный Природоохранный Центр" Nymphaea candida, Caltha palustris, Trollius europaeus, Bistorta major, Coccyganthe flos-cuculi, Steris viscaria, Dianthus fischeri, Lathyrus vernus, Fragaria viridis, Campanula patula, Campanula persicifolia, Campanula rotundifolia, Pulmonaria obscura, Polygonatum odoratum Neomys fodiens, Erinaceus europaeus, Nyctalus noctula, Mustela nivalis, Lepus europaeus, Lepus timidus, Anas querquedula, Anas clypeata, Aythya ferina, Aythya fuligula, Accipiter gentilis, Accipiter nisus, Falco tinnunculus, Porzana porzana, Crex crex, Gallinula chloropus, Fulica atra, Larus ridibundus, Larus canus, Sterna hirundo, Cuculus canorus, Asio otus, Strix aluco, Dendrocopos leucotos, Riparia riparia, Alauda arvensis, Motacilla flava, Lanius collurio, Locustella fluviatilis, Acrocephalus arundinaceus, Saxicola rubetra, Aegithalos caudatus, Natrix natrix, Rana temporaria, Rana arvalis, Leuciscus leuciscus, Leuciscus cephalus, Tinca tinca, Silurus glanis, Sympetrum pedemontanum, Tettigonia cantans, Decticus verrucivorus, Metrioptera brachyptera, Metrioptera bicolor, Prionus coriarius, Andrena hattorfiana, Anthidium manicatum, Anthidium punctatum, Hyponephele lycaon, Apatura ilia, Limenitis populi, Brenthis ino, Lycaena alciphron, Glaucopsyche alexis, Endromis versicolora, Aglia tau, Hemaris fuciformis Урбанозем гумусированный средне-сильномощный на флювиогляциальных песках и супесях, Дерново-средне-сильноурбоподзолистая слабо-средненарушенная на моренном и покровном суглинке, Слабо-среднедерново-урбоподзолистая на флювиогляциальных песках и супесях, Аллювиальные дерновые, луговые на аллювиальных. слоистых песчано-супесчаных отложениях, Индустризем малогумусный маломощный на насыпном и привозном грунте, Индустризем слабогумусированный мало-сильномощный на насыпном грунте или культурном слое, Почвы кладбищ (некроземы), nan, Индустризем малогумусный мало-среднемощный на культурном слое и покровном суглинке, Индустризем слабогумусированный мало-среднемощный на насыпном и привозном грунте , Урбанозем гумусированный слабо-среднемощный на моренно или покровном суглинке, Урбанозем гумусированный средне-сильномощный на культурном слое и покровном суглинке, Урбанозем гумусированный слабо-среднемощный, Слабо-среднедерново-слабо-средне-сильноурбоподзолистая на двучленных отложениях "Артиллерийский ДОТ Московской линии обороны, 1941 г.", "Главный дом (деревянный)", XVIII в., Дот, 1941 г., Загородная усадьба, XVIII в., Комплекс сооружений канала им. Москвы, 19321937 гг., Надгробие Николая Григорьевича Гурьева (1868 1905), "Парк", XVIII в., Усадьба "ТроицкоеЛыково", Усадьба "ФилиКунцево", "Флигель", XVIII в., "Храм Успения Пресвятой Богородицы в усадьбе Троице–Лыково, 1850–е гг., 1900–е гг., архитектор С.Ф.Кулагин", "Церковь в селе Крылатском", XVIII в., "Церковь Покрова в Филях", 1693–1694 гг., "Церковь Троицы", 1693 г., "Церковь Троицы", 1698 – 1704 гг., Шлюз 1, арх. Белдовский, Шлюз 2, арх. А.Л.Пастернак, Шлюз 4, арх. Г.Г.Вегман, А.Л.Пастернак, Шлюз 5, арх. Д.Б.Савицкий, Шлюз 78, арх. В.Ф.Кринский Нарушенность территорий невелика. На ООПТ присутствуют значительные по площади лесные массивы (два Серебряноборских и Фили-Кунцевский) и небольшие лесные островки (на Крылатских холмах и в Крылатской пойме), обширные луга и небольшие луговины, представляющие естественные биотопы Помимо постоянно действующих факторов антропогенного воздействия (фоновое загрязнение атмосферы, длительное хозяйственное использование и интенсивная урбанизация прилегающих территорий), можно выделить несколько локальных негативных факторов, наиболее значимых для данной территории. К ним относятся: - Выбросы автотранспорта, оказывающие значительное влияние на загрязнение атмосферного воздуха, а воздушный перенос способствует поступлению загрязняющих веществ в почвенный покров. Также при передвижении автотранспорта по автомобильным дорогам с различной степенью интенсивности движения увеличивается воздействие негативных физических факторов. Территория преобразована техногенной и антропогенной деятельностью объектов гидротехнических сооружений канала им. Москвы, рекреационным и спортивно-рекреационным освоением, антропогенной нагрузкой со стороны МКАД. 77:08:0002022:2, 77:08:0000000:3350, 77:08:0000000:6167, 77:08:0002022:4011, 77:08:0002023:2065, 77:08:0009001:9, 77:08:0009001:3924, 77:08:0006013:11, 77:08:0009001:54, 77:08:0007006:9, 77:08:0005006:19, 77:08:0005001:37, 77:08:0005001:1702, 77:08:0006007:3038, 77:08:0005010:5599, 77:08:0005010:11, 77:08:0005010:1000, 77:08:0005009:2754, 77:08:0005007:56, 77:08:0015001:3628, 77:08:0015001:1716, 77:08:0008001:3937, 77:08:0006012:16, 77:08:0005010:44, 77:08:0005009:43, 77:08:0005010:46, 77:08:0006007:29, 77:08:0015001:1770, 77:08:0005008:1296, 77:08:0005009:2755, 77:08:0005010:1522, 77:08:0006007:3047, 77:08:0015001:1717, 77:08:0012003:4141, 77:08:0010001:9017, 77:08:0010001:14, 77:08:0010001:1000, 77:08:0010016:1570, 77:08:0010016:1217, 77:08:0010016:3, 77:08:0010001:59, 77:08:0010016:2, 77:08:0010001:15, 77:08:0010001:9804, 77:08:0010016:1238, 77:08:0013001:117, 77:08:0013001:12, 77:08:0000000:6831, 77:08:0013002:6, 77:08:0013011:1540, 77:08:0013011:1506, 77:08:0013011:1001, 77:08:0013002:1101, 77:08:0013009:1000, 77:08:0013011:2, 77:08:0013011:1875, 77:08:0005001:1945, 77:08:0005001:1924, 77:08:0005005:79, 77:08:0005006:43, 77:08:0009021:2570, 77:08:0009021:1185, 77:07:0001003:1889, 77:07:0000000:6100, 77:07:0001003:1003, 77:07:0001003:1001, 77:07:0001003:1006, 77:07:0001003:1894, 77:07:0001003:2275, 77:07:0001003:2279, 77:07:0001003:2281, 77:07:0001004:1008, 77:07:0001004:1007, 77:07:0001004:1006, 77:07:0001004:2418, 77:07:0001004:2203, 77:07:0001004:2738, 77:07:0001004:2763, 77:07:0001004:2743, 77:08:0013011:1559, 77:07:0003003:3854, 77:07:0001003:1876, 77:07:0001003:1891, 77:07:0001003:36, 77:07:0001003:16, 77:07:0001003:1890, 77:00:0000000:73928, 77:08:0013011:3, 77:08:0013011:1, 77:08:0013011:1539, 77:08:0013011:1558, 77:07:0001003:22, 77:07:0001003:13, 77:08:0013014:2330, 77:08:0013014:1691, 77:07:0001004:7, 77:07:0001004:5, 77:07:0001004:42, 77:07:0001004:2202, 77:07:0001004:3105, 77:07:0001004:3101, 77:07:0001004:3098, 77:07:0001003:1005, 77:07:0001003:1004, 77:07:0001004:2744, 77:07:0001004:2742, 77:07:0001004:2737, 77:07:0001004:2697, 77:07:0001004:2426, 77:07:0001004:2425, 77:07:0001004:2424, 77:07:0001004:2423, 77:07:0001004:2422, 77:07:0001004:2421, 77:07:0001004:2226, 77:07:0001004:1009, 77:07:0001004:1005, 77:07:0001004:1004, 77:07:0001004:1003, 77:07:0001004:1002, 77:07:0001003:31, 77:07:0001003:2280, 77:07:0001003:2276, 77:07:0001003:1860, 77:07:0001003:1792, 77:07:0000000:6099, 77:07:0001003:2277, 77:07:0001003:1007, 77:07:0001004:6, 77:07:0001004:41, 77:07:0001004:32, 77:07:0001003:15, 77:07:0001004:37, 77:07:0001003:18, 77:07:0001003:30, 77:07:0001004:33, 77:07:0001004:3204, 77:07:0001004:4, 77:07:0001004:15, 77:07:0001004:1, 77:07:0001003:9, 77:08:0006015:20, 77:08:0006011:37, 77:08:0007003:22, 77:08:0006011:3007, 77:07:0003002:1909, 77:07:0003002:19, 77:07:0003002:1890, 77:07:0003002:1889, 77:07:0003002:1446, 77:07:0003002:1000, 77:07:0001001:12717, 77:07:0001001:9309, 77:07:0001001:1002, 77:07:0003002:14, 77:07:0003002:16, 77:07:0003002:18, 77:07:0003002:20, 77:07:0003002:21, 77:07:0003002:22, 77:07:0003002:23, 77:07:0003002:24, 77:07:0003002:25, 77:07:0003003:20, 77:07:0003001:17, 77:07:0003002:15, 77:07:0001001:42, 77:07:0003002:1577, 77:07:0003002:13, 77:07:0003002:10, 77:07:0003001:31, 77:07:0001001:11880, 77:07:0001001:8744, 77:07:0003002:1575, 77:07:0001001:8748, 77:07:0001001:74, 77:07:0001001:72, 77:07:0001001:29, 77:08:0013001:164, 77:08:0013001:15, 77:07:0001003:32, 77:08:0013011:5, 77:07:0001001:71, 77:07:0001001:1, 77:08:0008009:1000, 77:08:0008012:4, 77:08:0008010:3, 77:08:0008010:24, 77:08:0008010:23, 77:08:0008010:2, 77:08:0008010:17, 77:08:0008009:39, 77:08:0008010:1390, 77:08:0008010:1076, 77:08:0008010:1065, 77:08:0008010:1066, 77:08:0008010:1063, 77:08:0008010:1001, 77:08:0008009:5998, 77:08:0008009:5626, 77:08:0008012:1007, 77:08:0008010:4, 77:08:0008010:22, 77:08:0008001:4, 77:08:0008009:48, 77:08:0008009:47, 77:08:0008010:9, 77:08:0008001:67, 77:08:0008009:54, 77:08:0008010:1069, 77:08:0008009:5997, 77:08:0008010:1000, 77:08:0008010:1004, 77:08:0009021:2568, 77:08:0009021:1001, 77:08:0009021:1230, 77:08:0002017:1916, 77:08:0002016:9354, 77:08:0002016:8268, 77:08:0002016:4576, 77:08:0000000:1042, 77:08:0002016:4451, 77:08:0002001:292, 77:08:0000000:7073, 77:08:0002014:2354, 77:08:0002014:2356, 77:08:0002014:2357, 77:08:0002014:2355, 77:08:0002014:2353, 77:08:0000000:3315, 77:08:0000000:7247, 77:08:0002016:4450, 77:08:0002016:7077, 77:08:0002016:7075, 77:08:0002014:2814, 77:07:0003001:28, 77:07:0003001:2636, 77:07:0003001:23, 77:07:0003001:25, 77:07:0003001:27, 77:07:0000000:13622, 77:07:0003001:22, 77:07:0003001:34, 77:07:0003001:1001, 77:07:0003003:21, 77:07:0003001:36, 77:07:0003001:35, 77:07:0003001:32, 77:07:0003001:29, 77:07:0003001:26, 77:07:0003001:24, 77:07:0003001:1000, 77:07:0003001:2633, 77:07:0003001:30, 77:08:0009021:1000, 77:08:0009021:1007, 77:08:0013013:59, 77:08:0008010:1064, 77:08:0008010:1003, 77:08:0010016:1253, 77:08:0010016:1255, 77:08:0013012:1703, 77:08:0010001:62, 77:08:0010001:39, 77:08:0010001:25, 77:08:0008010:1, 77:08:0009021:32, 77:08:0008010:1068, 77:08:0013013:1016, 77:08:0013001:77, 77:08:0013001:27, 77:08:0013011:4, 77:08:0013009:1002, 77:08:0013002:9, 77:08:0013010:1795, 77:08:0002016:8273, 77:08:0002016:8267, 77:08:0002016:8266, 77:08:0002016:8265, 77:08:0002016:8261, 77:08:0002016:7080, 77:08:0002016:7076, 77:08:0002016:4453, 77:08:0002016:4452, 77:08:0002014:2813, 77:08:0002016:8264, 77:08:0008001:69, 77:08:0008001:66, 77:08:0008001:36, 77:08:0008001:1009, 77:08:0008001:1006, 77:08:0008001:1000, 77:08:0008001:68, 77:08:0015001:44, 77:08:0005010:22, 77:08:0008001:50, 77:08:0015001:23, 77:08:0005010:8, 77:08:0015001:1001, 77:07:0005008:101, 77:07:0005010:16, 77:07:0005010:1928, 77:07:0005010:1935, 77:08:0002023:2384, 77:08:0002023:2383, 77:08:0002022:3998, 77:08:0002011:89, 77:08:0002022:17, 77:08:0002023:2064, 77:08:0013009:3, 77:08:0013009:2, 77:08:0008010:1002, 77:08:0013003:147, 77:08:0013001:157, 77:08:0013009:1160, 77:08:0013011:1542, 77:08:0013009:10

In [34]:
# Получаем NER компонент
ner = nlp.get_pipe("ner")

In [35]:
# добавляем новые labels
for label in entities_values:
    if label not in ner.labels:
        ner.add_label(label)
        print(f"Добавлен новый label: {label}")

Добавлен новый label: DISTRICT

In [36]:
# отключаем все остальные pipe
other_pipes = [pipe for pipe in nlp.pipe_names if pipe != "ner"]
with nlp.disable_pipes(*other_pipes):
    optimizer = nlp.resume_training()

In [37]:
# 
iteration_number = 5
for iteration in range(iteration_number):
    random.shuffle(resolved_annotated_examples)
    losses = {}
    for example in resolved_annotated_examples:
        text = example[0]
        annotations = example[1]
        doc = nlp.make_doc(text)
        train_example = Example.from_dict(doc, annotations)
        nlp.update([train_example], sgd=optimizer, losses=losses, drop=0.4)
    if iteration % 5 == 0:
        print(f"Iteration {iteration}, Loss: {losses['ner']}")

Iteration 0, Loss: 3221.941162109375

KeyboardInterrupt:

In [35]:
# сохранение модели
ner = nlp.get_pipe('ner')
# ner.to_disk('../files')

In [36]:
# загрузка модели
# nlp = spacy.load('ru_core_news_lg', disable=['ner'])
# ner = EntityRecognizer(nlp.vocab)
# ner.from_disk('/usr/to/ner')
# nlp.add_pipe(ner, "custom_ner")
# 
# print(nlp.meta['pipeline'])

In [37]:
# работа обновленной модели
sample_text = ('ЦАО Пресненский (ЦАО) 159 158 Постановление Правительства Москвы от 01.10.2020 № 1642-ПП \"Об образовании особо охраняемых природных территорий регионального значения - памятников природы в городе Москве\" аккумулятивный полого-волнистый моренный рельеф Префектура ЦАО, ГБУ \"Автомобильные Дороги ЦАО\" '
               'Лосиный остров СВАО САО')

doc = nlp(sample_text)
entities = []
for ent in doc.ents:
    entities.append({
        'text': ent.text,
        'label': ent.label_,
        'start': ent.start_char,
        'end': ent.end_char
    })
for i, ent in enumerate(entities, 1):
    print(f"{i}. {ent['text']} -> {ent['label']} ({ent['start']}-{ent['end']})")
displacy.render(doc, style="ent", jupyter=True)

1. ЦАО Пресненский -> PER (0-15)
2. ЦАО -> DISTRICT (17-20)
3. Москвы -> LOC (58-64)
4. Москве -> LOC (196-202)
5. Префектура -> LOC (252-262)
6. ЦАО -> DISTRICT (263-266)
7. ГБУ "Автомобильные Дороги ЦАО" Лосиный остров -> ORG (268-313)
8. СВАО -> LOC (314-318)
9. САО -> DISTRICT (319-322)